### ISSUE TITLE
Release for swift 3?

### ISSUE THREAD

**Issue by rlam3** [brynbellomy/SwiftFlatUIColors#9]
Release for swift 3?

**Comment by alapergola** [comment]
Just replace the public static fun colorFromHexCode with this piece of code: 

    var cString:String = hex.stringByTrimmingCharactersInSet(NSCharacterSet.whitespaceAndNewlineCharacterSet() as NSCharacterSet).uppercaseString

    if (cString.hasPrefix("#")) {
      cString = cString.substringFromIndex(cString.startIndex.advancedBy(1))
    }

    if ((cString.characters.count) != 6) {
      return UIColor.grayColor()
    }

    var rgbValue:UInt32 = 0
    NSScanner(string: cString).scanHexInt(&rgbValue)

(until the declaration of the red, green, blue, if you don't want to mess up with the return.

In short the whole function became:

```
    public static func colorFromHexCode(_ hex:String) -> OSColor!
    {
        var cString:String = hex.stringByTrimmingCharactersInSet(NSCharacterSet.whitespaceAndNewlineCharacterSet() as NSCharacterSet).uppercaseString
        
        if (cString.hasPrefix("#")) {
            cString = cString.substringFromIndex(cString.startIndex.advancedBy(1))
        }
        
        if ((cString.characters.count) != 6) {
            return UIColor.grayColor()
        }
        
        var rgbValue:UInt32 = 0
        NSScanner(string: cString).scanHexInt(&rgbValue)

        let red     = CGFloat(r) / 255.0
        let green   = CGFloat(g) / 255.0
        let blue    = CGFloat(b) / 255.0
        let alpha   = CGFloat(a) / 255.0
        return OSColor(red:red, green:green, blue:blue, alpha:alpha)
    }

```

it should work (at least it works for me).

**Comment by picaso** [comment]
Any update on this?

**Comment by picaso** [comment]
There is a pull request to fix this from @Jauzee @brynbellomy

**Comment by brynbellomy** [comment]
Merged, thanks!
